### ISSUE TITLE
codm global error

### ISSUE THREAD

**Issue by Viktor2049** [tien0246/Il2CppDumper-for-COD#6]
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\Users\TIEN\Desktop\Il2CppDumper cod\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 246
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\Users\TIEN\Desktop\Il2CppDumper cod\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 102
   at Il2CppDumper.Elf64.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\Users\TIEN\Desktop\Il2CppDumper cod\Il2CppDumper\ExecutableFormats\Elf64.cs:line 97
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\Users\TIEN\Desktop\Il2CppDumper cod\Il2CppDumper\Program.cs:line 210

**Comment by tien0246** [comment]
Fixed!
